# Préface {.unnumbered}

Cette page Quarto est une collection d'exercices distribués par l'autrice dans le cadre du cours ACT-2000 \emph{Analyse statistique des risques
actuariels} à l'École d'actuariat de l'Université Laval. Certains
exercices sont le fruit de l'imagination des auteurs du recueil ou des versions précédentes, alors que plusieurs autres sont des adaptations d'exercices tirés des ouvrages cités dans la bibliographie.

C'est d'ailleurs afin de ne pas usurper de droits d'auteur que ce
document est publié selon les termes du contrat Paternité-Partage des
conditions initiales à l'identique 2.5 Canada de Creative Commons. Il
s'agit donc d'un document «libre» que quiconque peut réutiliser et
modifier à sa guise, à condition que le nouveau document soit publié
avec le même contrat.

Le recueil d'exercices se veut un complément à un cours de statistique
mathématique pour des étudiants de premier cycle
universitaire. Les exercices sont divisés en six chapitres qui
correspondent aux chapitres de notre cours. Le
chapitre 1 porte sur les modèles statistiques de base et comprend la notion
d'échantillon aléatoire, quelques rappels de probabilité, ainsi que la notion de statistique d'ordre. Il est suivi du chapitre 2 qui traite des distributions d'échantillonnage et présente les distributions liées à la loi normale, soit la loi $t$ de Student, la loi du khi carré, et la distribution de Fisher--Snedecor. 

Au chapitre 3, on aborde les diverses propriétés des estimateurs.
Le chapitre 4 traite d'estimation ponctuelle par
les méthodes classiques (maximum de vraisemblance, méthode des
moments, etc.). Enfin, les notions étroitement liées d'estimation par intervalle et 
de test d'hypothèses font l'objet des chapitres 5 et 6.

On trouvera sur le site de cours
 une liste non exhaustive d'exercices proposés dans
@Wackerly:mathstat:7e:2008. Des solutions de ces exercices
sont offertes dans @Wackerly:solutions:7e:2008.

J'encourage le lecteur à utiliser le logiciel R [@R] pour résoudre certains exercices.

Je remercie Vincent Mercier pour son aide dans la préparation de ce recueil. Je remercie aussi d'avance les lecteurs qui voudront bien me faire
part de toute erreur ou omission dans les exercices ou leurs
solutions.

Marie-Pier Côté \url{<marie-pier.cote@act.ulaval.ca>} \\
Québec, juin 2026