<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Estimation par intervalle – ACT2000 — Recueil d'exercices</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapitres/tests.html" rel="next">
<link href="../chapitres/ajustement.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-a522afb83bf8ae494942cf1b0ac9d4c3.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Pas de résultats",
    "search-matching-documents-text": "documents trouvés",
    "search-copy-link-title": "Copier le lien vers la recherche",
    "search-hide-matches-text": "Cacher les correspondances additionnelles",
    "search-more-match-text": "correspondance de plus dans ce document",
    "search-more-matches-text": "correspondances de plus dans ce document",
    "search-clear-button-title": "Effacer",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Annuler",
    "search-submit-button-title": "Envoyer",
    "search-label": "Recherche"
  }
}</script>
<script>
window.MathJax = {
  tex: {
    macros: {
      esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      Esp:    ["\\mathbb{E}\\!\\left[#1\\right]", 1],
      ex:     "\\mathbb{E}",
      var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      Var:    ["\\mathrm{Var}\\!\\left(#1\\right)", 1],
      vr:     "\\mathrm{Var}",
      prob:   ["\\Pr\\!\\left[#1\\right]", 1],
      Prob:   ["\\Pr\\!\\left[#1\\right]", 1],
      Cov:    "\\mathrm{Cov}",
      d:      "\\mathrm{d}",
      bm:     ["\\boldsymbol{#1}", 1],
      abs: ["\\left|#1\\right|", 1],
      texttt: ["`#1`", 1],
      textsf: ["`#1`", 1]
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/base.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/intervalle.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimation par intervalle</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Basculer la barre latérale" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Recherche" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">ACT2000 — Recueil d’exercices</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Recherche"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Exercices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Basculer la section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/base.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Modèles statistiques de base</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/echantillonnage.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Distributions d’échantillonnage</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Estimation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/ajustement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ajustement de modèles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/intervalle.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimation par intervalle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapitres/tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#sec-intervalle-pivot_gamma" id="toc-sec-intervalle-pivot_gamma" class="nav-link active" data-scroll-target="#sec-intervalle-pivot_gamma"><span class="header-section-number">5.1</span> Pivot pour le paramètre d’échelle d’une loi gamma</a></li>
  <li><a href="#sec-intervalle-moyenne_normale" id="toc-sec-intervalle-moyenne_normale" class="nav-link" data-scroll-target="#sec-intervalle-moyenne_normale"><span class="header-section-number">5.2</span> Intervalle de confiance pour la moyenne d’une loi normale avec variance connue</a></li>
  <li><a href="#sec-intervalle-taille_pour_couverture" id="toc-sec-intervalle-taille_pour_couverture" class="nav-link" data-scroll-target="#sec-intervalle-taille_pour_couverture"><span class="header-section-number">5.3</span> Taille d’échantillon aléatoire pour atteindre un niveau de confiance</a></li>
  <li><a href="#sec-intervalle-intervalles_mu_sigma" id="toc-sec-intervalle-intervalles_mu_sigma" class="nav-link" data-scroll-target="#sec-intervalle-intervalles_mu_sigma"><span class="header-section-number">5.4</span> Intervalles de confiance pour les paramètres d’une loi normale</a></li>
  <li><a href="#sec-intervalle-taille_etudiants" id="toc-sec-intervalle-taille_etudiants" class="nav-link" data-scroll-target="#sec-intervalle-taille_etudiants"><span class="header-section-number">5.5</span> Tailles des étudiantes en actuariat et en génie civil</a></li>
  <li><a href="#sec-intervalle-intervalle_sigma" id="toc-sec-intervalle-intervalle_sigma" class="nav-link" data-scroll-target="#sec-intervalle-intervalle_sigma"><span class="header-section-number">5.6</span> Estimateur par intervalle pour <span class="math inline">\(\sigma\)</span></a></li>
  <li><a href="#sec-intervalle-taille_longueur_intervalle" id="toc-sec-intervalle-taille_longueur_intervalle" class="nav-link" data-scroll-target="#sec-intervalle-taille_longueur_intervalle"><span class="header-section-number">5.7</span> Taille d’échantillon pour obtenir une certaine longueur d’intervalle</a></li>
  <li><a href="#sec-intervalle-taille_longueur_minimale" id="toc-sec-intervalle-taille_longueur_minimale" class="nav-link" data-scroll-target="#sec-intervalle-taille_longueur_minimale"><span class="header-section-number">5.8</span> Conditions pour obtenir une longueur minimale d’intervalle de confiance</a></li>
  <li><a href="#sec-intervalle-resultats_sat" id="toc-sec-intervalle-resultats_sat" class="nav-link" data-scroll-target="#sec-intervalle-resultats_sat"><span class="header-section-number">5.9</span> Résultats au SAT</a></li>
  <li><a href="#sec-intervalle-laboratoires_cuivre" id="toc-sec-intervalle-laboratoires_cuivre" class="nav-link" data-scroll-target="#sec-intervalle-laboratoires_cuivre"><span class="header-section-number">5.10</span> Laboratoires de production de cuivre</a></li>
  <li><a href="#sec-intervalle-aines_cycles_superieurs" id="toc-sec-intervalle-aines_cycles_superieurs" class="nav-link" data-scroll-target="#sec-intervalle-aines_cycles_superieurs"><span class="header-section-number">5.11</span> Enfants aînés aux cycles supérieurs</a></li>
  <li><a href="#sec-intervalle-intervalle_mle_exponentielle" id="toc-sec-intervalle-intervalle_mle_exponentielle" class="nav-link" data-scroll-target="#sec-intervalle-intervalle_mle_exponentielle"><span class="header-section-number">5.12</span> Intervalle de confiance avec l’estimateur du maximum de vraisemblance d’une distribution exponentielle</a></li>
  <li><a href="#sec-intervalle-intervalle_mle_bernoulli" id="toc-sec-intervalle-intervalle_mle_bernoulli" class="nav-link" data-scroll-target="#sec-intervalle-intervalle_mle_bernoulli"><span class="header-section-number">5.13</span> Intervalle de confiance avec l’estimateur du maximum de vraisemblance d’une distribution Bernoulli</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapitres/base.html">Exercices</a></li><li class="breadcrumb-item"><a href="../chapitres/intervalle.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimation par intervalle</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Estimation par intervalle</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-intervalle-pivot_gamma" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-intervalle-pivot_gamma"><span class="header-section-number">5.1</span> Pivot pour le paramètre d’échelle d’une loi gamma</h2>
<p>Soit <span class="math inline">\(X_1, \ldots, X_n\)</span> un échantillon aléatoire de taille <span class="math inline">\(n\)</span> tiré d’une distribution Gamma avec paramètres <span class="math inline">\(\alpha=2\)</span> et <span class="math inline">\(\beta\)</span> inconnu.</p>
<p><strong>a)</strong> Montrer que <span class="math inline">\(T = 2(X_1 +\cdots+X_n)/\beta\)</span> est un pivot et que sa distribution est khi-carrée avec <span class="math inline">\(4n\)</span> degrés de liberté.</p>
<p><em>Astuce:</em> utiliser les fonctions génératrices des moments.</p>
<p><strong>b)</strong> Utiliser le pivot <span class="math inline">\(T\)</span> pour construire un intervalle de confiance bilatéral de niveau 95 % pour <span class="math inline">\(\beta\)</span>.</p>
<p><strong>c)</strong> Si la moyenne échantillonnale est de <span class="math inline">\(\bar x = 5,6\)</span> et que <span class="math inline">\(n=5\)</span>, utiliser le résultat en b) pour donner un intervalle de confiance de niveau 95 % pour <span class="math inline">\(\mu\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> La fonction génératrice des moments d’une distribution Gamma avec paramètres <span class="math inline">\(\alpha = 2\)</span> et <span class="math inline">\(\beta &gt; 0\)</span> est donnée par <span class="math display">\[ M_X(t) = (1-\beta t)^{-2}, \quad t &lt; 1/\beta. \]</span> La fonction génératrice des moments de <span class="math inline">\(T = 2(X_1 + \cdots + X_n)/\beta\)</span> est donc <span class="math display">\[ M_T(t) = \ex (e^{(2t/\beta) \sum_{i=1}^n X_i}) = \prod_{i=1}^n \ex \left\{ e^{(2t/\beta) X_i} \right\} = \{ M_X(2t/\beta)\}^n = (1-2t)^{-2n} \]</span> à condition que <span class="math inline">\(2t/\beta &lt; 1/\beta\)</span>, i.e., si <span class="math inline">\(t &lt; 1/2\)</span>. Sachant que <span class="math inline">\((1-2t)^{-2n}\)</span> est la fonction génératrice des moments d’une distribution khi-carrée avec <span class="math inline">\(4n\)</span> degrés de liberté, <span class="math inline">\(T \sim \chi^2_{(4n)}\)</span>. Ainsi, <span class="math inline">\(T\)</span> est une fonction de l’échantillon aléatoire et du paramètre <span class="math inline">\(\beta\)</span>, avec une distribution connue qui ne dépend d’aucun paramètre inconnu&nbsp;: <span class="math inline">\(T\)</span> est donc un pivot.</p>
<p><strong>b)</strong> Pour construire l’intervalle de confiance bilatéral à partir de <span class="math inline">\(T\)</span>, on note <span class="math inline">\(\chi^2_{0,975,   4n}\)</span> et <span class="math inline">\(\chi^2_{0,025,   4n}\)</span> les quantiles <span class="math inline">\(2,5\%\)</span> et <span class="math inline">\(97,5\%\)</span></p>
<p><span class="math display">\[
\begin{aligned} \chi^2_{0,975,   4n} \le T \le \chi^2_{0,025,   4n} \\ \chi^2_{0,975,   4n} \le \frac{2}{\beta} \sum_{i=1}^n X_i \le \chi^2_{0,025,   4n} \\ \frac{\chi^2_{0,975,   4n} }{2\sum_{i=1}^n X_i}  \le \frac{1}{\beta}  \le \frac{\chi^2_{0,025,   4n}}{2\sum_{i=1}^n X_i} \\ \frac{2n \bar{X}_n}{\chi^2_{0,025,   4n} }  \le \beta  \le \frac{2n \bar{X}_n}{\chi^2_{0,975,   4n}}, \end{aligned}
\]</span> ce qui donne un l’intervalle de confiance bilatéral de niveau <span class="math inline">\(95\)</span>%</p>
<p><span class="math display">\[
\begin{aligned} \left[ \frac{2n \bar X_n}{ \chi^2_{0,025,   4n}}   , \frac{2n \bar X_n}{ \chi^2_{0,975,   4n}}\right]. \end{aligned}
\]</span></p>
<p><strong>c)</strong> Avec <span class="math inline">\(n = 5\)</span>, les quantiles requis d’une distribution khi-carrée avec <span class="math inline">\(4n = 20\)</span> degrés de liberté sont</p>
<p><span class="math display">\[
\begin{aligned}
\chi^2_{0,975,   20} = 9.59, &amp;\quad  \chi^2_{0,025,   20} = 34.17.
\end{aligned}
\]</span></p>
<p>Sachant que <span class="math inline">\(\bar x_n = 5,6\)</span>, l’intervalle de confiance de niveau <span class="math inline">\(95\)</span>% est</p>
<p><span class="math display">\[
\begin{aligned} \left[ \frac{2\times 5\times 5,6}{ 34.17}   , \frac{2\times 5\times 5,6}{ 9.59}\right] = [ 1.64, 5.84].
\end{aligned}
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-moyenne_normale" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="sec-intervalle-moyenne_normale"><span class="header-section-number">5.2</span> Intervalle de confiance pour la moyenne d’une loi normale avec variance connue</h2>
<p>La valeur observée de la moyenne empirique <span class="math inline">\(\bar{X}\)</span> d’un échantillon aléatoire de taille <span class="math inline">\(20\)</span> tiré d’une <span class="math inline">\(N(\mu, 80)\)</span> est <span class="math inline">\(81,2\)</span>. Déterminer un estimateur par intervalle de niveau <span class="math inline">\(95\%\)</span> pour <span class="math inline">\(\mu\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\((77,28,   85,12)\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On cherche deux statistiques <span class="math inline">\(L\)</span> et <span class="math inline">\(U\)</span> tel que <span class="math display">\[
      \prob{L \leq \mu \leq U} = 1 - \alpha.
    \]</span> On sait que si <span class="math inline">\(X_1, \dots, X_n\)</span> est un échantillon aléatoire tiré d’une distribution <span class="math inline">\(N(\mu, \sigma^2)\)</span>, alors <span class="math inline">\(\bar{X} \sim N(\mu,
    \sigma^2/n)\)</span> ou, de manière équivalente, que <span class="math display">\[
      \frac{\bar{X} - \mu}{\sigma / \sqrt{n}} \sim N(0, 1).
    \]</span> Par conséquent, <span class="math display">\[
      \Prob{-z_{\alpha/2} \leq \frac{\bar{X} - \mu}{\alpha/\sqrt{n}} \leq
        z_{\alpha/2}} = 1 - \alpha,
    \]</span> d’où <span class="math display">\[
      \Prob{\bar{X} - \frac{\sigma}{\sqrt{n}}  z_{\alpha/2} \leq \mu
        \leq \bar{X} + \frac{\sigma}{\sqrt{n}}  z_{\alpha/2}} = 1 - \alpha.
    \]</span> Les statistiques <span class="math inline">\(L\)</span> et <span class="math inline">\(U\)</span> sont dès lors connues: <span class="math inline">\(L = \bar{X} -
    \sigma z_{\alpha/2}/\sqrt{n}\)</span> et <span class="math inline">\(U = \bar{X} + \sigma
    z_{\alpha/2}/\sqrt{n}\)</span>. Un estimateur par intervalle de <span class="math inline">\(\mu\)</span> est donc <span class="math display">\[
      (\bar{X} - \sigma z_{\alpha/2}/\sqrt{n},
      \bar{X} + \sigma z_{\alpha/2}/\sqrt{n}).
    \]</span> Avec <span class="math inline">\(n = 20\)</span>, <span class="math inline">\(\sigma^2 = 80\)</span> et <span class="math inline">\(\bar{x} = 81,2\)</span>, on obtient l’intervalle <span class="math inline">\((77,28, \; 85,12)\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-taille_pour_couverture" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sec-intervalle-taille_pour_couverture"><span class="header-section-number">5.3</span> Taille d’échantillon aléatoire pour atteindre un niveau de confiance</h2>
<p>Soit <span class="math inline">\(\bar{X}\)</span> la moyenne d’un échantillon aléatoire de taille <span class="math inline">\(n\)</span> d’une distribution normale de moyenne <span class="math inline">\(\mu\)</span> inconnue et de variance <span class="math inline">\(9\)</span>. Trouver la valeur <span class="math inline">\(n\)</span> tel que, approximativement, <span class="math inline">\(\prob{\bar{X} - 1 &lt; \mu &lt; \bar{X} + 1} = 0,90\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(24\)</span> ou <span class="math inline">\(25\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On a <span class="math inline">\(X \sim N(\mu, 9)\)</span>. Tel que démontré à l’exercice <a href="#sec-intervalle-moyenne_normale" class="quarto-xref"><span>5.2</span></a>, <span class="math display">\[
      \Prob{\bar{X} - \frac{\sigma}{\sqrt{n}}  z_{0,05} \leq \mu
        \leq \bar{X} + \frac{\sigma}{\sqrt{n}}  z_{0,05}} = 0,90.
    \]</span> Pour satisfaire la relation <span class="math inline">\(\prob{\bar{X} - 1 &lt; \mu &lt; \bar{X} +
      1} = 0,90\)</span>, on doit donc choisir <span class="math display">\[
      \frac{\sigma}{\sqrt{n}}  z_{0,05} =
      \frac{3 (1,645)}{\sqrt{n}} = 1.
    \]</span> On trouve que <span class="math inline">\(n = 24,35\)</span>. On doit donc choisir une taille d’échantillon de <span class="math inline">\(24\)</span> ou <span class="math inline">\(25\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-intervalles_mu_sigma" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="sec-intervalle-intervalles_mu_sigma"><span class="header-section-number">5.4</span> Intervalles de confiance pour les paramètres d’une loi normale</h2>
<p>Un échantillon aléatoire comptant <span class="math inline">\(17\)</span> observations d’une distribution normale de moyenne et de variance inconnues a donné <span class="math inline">\(\bar{x} = 4,7\)</span> et <span class="math inline">\(s^2 = 5,76\)</span>. Trouver des intervalles de confiance à <span class="math inline">\(90\%\)</span></p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\mu \in (3,7, \; 5,7)\)</span> et <span class="math inline">\(\sigma^2 \in (3,50, \; 11,58)\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On sait que</p>
<p><span class="math display">\[
\begin{aligned}
      \frac{\bar{X} - \mu}{S/\sqrt{n}} &amp;\sim t(n-1) \\
      \end{aligned}
\]</span></p>
<p>et que</p>
<p><span class="math display">\[
\begin{aligned}
      \frac{(n-1) S^2}{\sigma^2} &amp;\sim \chi^2(n - 1).
    \end{aligned}
\]</span></p>
<p>Ainsi, on peut établir que <span class="math display">\[
      \Prob{\bar{X} - \frac{S}{\sqrt{n}}  t_{\alpha/2} \leq \mu
        \leq \bar{X} + \frac{S}{\sqrt{n}}  t_{\alpha/2}} = 1 - \alpha.
    \]</span> et qu’un intervalle de confiance de niveau <span class="math inline">\(1 - \alpha\)</span> pour <span class="math inline">\(\mu\)</span> est <span class="math display">\[
      (\bar{X} - S t_{\alpha/2}/\sqrt{n},  
      \bar{X} + S t_{\alpha/2}/\sqrt{n}).
    \]</span> Avec <span class="math inline">\(n = 17\)</span>, <span class="math inline">\(\bar{x} = 4,7\)</span>, <span class="math inline">\(s^2 = 5,76\)</span> et <span class="math inline">\(\alpha = 0,10\)</span>, on trouve que <span class="math inline">\(\mu \in (3,7,  5,7)\)</span>.</p>
<p>Pour la variance, on cherche des valeurs <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span>, <span class="math inline">\(a \leq b\)</span> tel que <span class="math display">\[
      \Prob{a \leq \frac{(n-1)S^2}{\sigma^2} \leq b} =
      \Prob{\frac{(n-1)S^2}{b} \leq \sigma^2 \leq \frac{(n-1)S^2}{a}} =
      1 - \alpha.
    \]</span> Plusieurs valeurs de <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> satisfont cette relation. Le choix le plus simple est <span class="math inline">\(a = \chi_{1 - \alpha/2}^2(n - 1)\)</span> et <span class="math inline">\(b =
    \chi_{\alpha/2}^2(n - 1)\)</span>. Ainsi, un intervalle de confiance de niveau <span class="math inline">\(1 - \alpha\)</span> pour <span class="math inline">\(\sigma^2\)</span> est <span class="math display">\[
      \left(
        \frac{(n-1)S^2}{\chi_{\alpha/2}^2(n - 1)},  
        \frac{(n-1)S^2}{\chi_{1 - \alpha/2}^2(n - 1)}
      \right).
\]</span> Dans une table de la loi khi carré, on trouve que <span class="math inline">\(\chi_{0,05}^2(16) = 7,96\)</span> et que <span class="math inline">\(\chi_{0,95}^2(16) = 26,30\)</span>, d’où <span class="math inline">\(\sigma^2 \in (3,50, \; 11,58)\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-taille_etudiants" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="sec-intervalle-taille_etudiants"><span class="header-section-number">5.5</span> Tailles des étudiantes en actuariat et en génie civil</h2>
<p>Lors d’une très sérieuse et importante analyse statistique de la taille des étudiantes en sciences et génie à l’Université Laval, on a mesuré un échantillon aléatoire d’étudiantes en actuariat et un autre en génie civil. Les résultats obtenus se trouvent résumés dans le tableau ci-dessous. On suppose que les deux échantillons aléatoires sont indépendants et que la taille des étudiantes est distribuée selon une loi normale.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'knitr' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantité</th>
<th style="text-align: right;">Actuariat</th>
<th style="text-align: right;">Génie.civil</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Taille de l’échantillon</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taille moyenne (en cm)</td>
<td style="text-align: right;">152</td>
<td style="text-align: right;">154</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Variance (en cm²)</td>
<td style="text-align: right;">101</td>
<td style="text-align: right;">112</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a)</strong> Déterminer un intervalle de confiance à <span class="math inline">\(90~\%\)</span> pour la taille moyenne des étudiantes de chacun des deux programmes en supposant que l’écart type de la distribution normale est 9 cm.</p>
<p><strong>b)</strong> Répéter la partie a) en utilisant plutôt les variances des échantillons.</p>
<p><strong>c)</strong> On suppose que les variances des deux populations sont égales. Y a-t-il une différence significative, avec un niveau de confiance de <span class="math inline">\(90~\%\)</span>, entre la taille des étudiantes en actuariat et celles en génie civil?</p>
<p><strong>d)</strong> Déterminer un intervalle de confiance à <span class="math inline">\(90~\%\)</span> pour la variance de la taille des étudiantes en actuariat.</p>
<p><strong>e)</strong> On suppose que les moyennes des deux populations sont égales. La différence observée entre les variances dans la taille des étudiantes des deux programmes est-elle significative? Utiliser un niveau de confiance de <span class="math inline">\(90~\%\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <span class="math inline">\(148,18 &lt; \mu_1 &lt; 155,82\)</span> et <span class="math inline">\(150,69 &lt; \mu_2 &lt; 157,31\)</span></p>
<p><strong>b)</strong> <span class="math inline">\(147,43 &lt; \mu_1 &lt; 156,57\)</span> et <span class="math inline">\(149,91 &lt; \mu_2 &lt; 158,09\)</span></p>
<p><strong>c)</strong> <span class="math inline">\(\mu_1 - \mu_2 \in -2 \pm 5,82\)</span></p>
<p><strong>d)</strong> <span class="math inline">\(59,71 &lt; \sigma_1^2 &lt; 215,22\)</span></p>
<p><strong>e)</strong> <span class="math inline">\(0,462 &lt; \sigma_2^2/\sigma_1^2 &lt; 2,502\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On représente la taille des étudiantes en actuariat par la variable aléatoire <span class="math inline">\(X\)</span> et celle des étudiantes en génie civil par <span class="math inline">\(Y\)</span>. On a <span class="math display">\[
\begin{aligned}
      \bar{X} &amp;\sim N(\mu_1, \sigma_1^2/15), &amp;
      \bar{Y} &amp;\sim N(\mu_2, \sigma_2^2/20), \\
      \frac{14 S_1^2}{\sigma_1^2} &amp;\sim \chi^2(14), &amp;
      \frac{19 S_2^2}{\sigma_2^2} &amp;\sim \chi^2(19)
    \end{aligned}
\]</span> et les valeurs des statistiques pour les deux échantillons sont <span class="math display">\[
\begin{aligned}
      \bar{x} &amp;= 152, &amp; \bar{y} &amp;= 154, \\
      s_1^2   &amp;= 101, &amp;  s_2^2  &amp;= 112.
    \end{aligned}
\]</span> <strong>a)</strong> Si l’on suppose que <span class="math inline">\(\sigma_1^2 = \sigma_2^2 = 81\)</span>, alors <span class="math inline">\(\bar{X} \sim N(\mu_1, 5,4)\)</span> et <span class="math inline">\(\bar{Y} \sim N(\mu_2, 4,05)\)</span>. Par conséquent, <span class="math display">\[
\Prob{-1,645 &lt; \frac{\bar{X} - \mu_1}{\sqrt{5,4}} &lt; 1,645} = 0,90
\]</span></p>
<p>et</p>
<p><span class="math display">\[
\begin{aligned} \Prob{-1,645 &lt; \frac{\bar{Y} - \mu_2}{\sqrt{4,05}} &lt; 1,645 } = 0,90,
\end{aligned}
\]</span></p>
<p>d’où</p>
<p><span class="math display">\[
152 - 1,645 \sqrt{5,4} &lt; \mu_1 &lt; 152 + 1,645 \sqrt{5,4},
\]</span></p>
<p>soit <span class="math inline">\(148,18 &lt; \mu_1 &lt; 155,82\)</span> et</p>
<p><span class="math display">\[
154 - 1,645 \sqrt{4,05} &lt; \mu_2 &lt; 154 + 1,645 \sqrt{4,05},
\]</span> soit <span class="math inline">\(150,69 &lt; \mu_2 &lt; 157,31\)</span>.</p>
<p><strong>b)</strong> Si la variance est inconnue, on a plutôt que</p>
<p><span class="math display">\[
\frac{\bar{X} - \mu_1}{S_1/\sqrt{15}} \sim t(14) \quad \text{et} \quad \frac{\bar{Y} - \mu_2}{S_2/\sqrt{20}} \sim t(19).
\]</span></p>
<p>Or, <span class="math inline">\(t_{0,05}(14) = 1,761\)</span> et <span class="math inline">\(t_{0,05}(19) = 1,729\)</span>, d’où</p>
<p><span class="math display">\[
152 - 1,761 \sqrt{\frac{101}{15}} &lt; \mu_1 &lt; 152 + 1,761 \sqrt{\frac{101}{15}},
\]</span></p>
<p>soit <span class="math inline">\(147,43 &lt; \mu_1 &lt; 156,57\)</span> et</p>
<p><span class="math display">\[
154 - 1,729 \sqrt{\frac{112}{20}} &lt; \mu_2 &lt; 154 + 1,729 \sqrt{\frac{112}{20}},
\]</span> soit <span class="math inline">\(149,91 &lt; \mu_2 &lt; 158,09\)</span>.</p>
<p><strong>c)</strong> On cherche un intervalle de confiance à <span class="math inline">\(90~\%\)</span> pour la différence <span class="math inline">\(\mu_1 - \mu_2\)</span>. Si <span class="math inline">\(0\)</span> appartient à l’intervalle, on pourra dire que la différence entre les deux moyennes n’est pas significative à <span class="math inline">\(90~\%\)</span>. Pour les besoins de la cause, on va supposer ici que <span class="math inline">\(\sigma_1^2 = \sigma_2^2 = \sigma^2\)</span>.</p>
<p>Or, puisque</p>
<p><span class="math display">\[
        \frac{(\bar{X} - \bar{Y}) - (\mu_1 - \mu_2)}{%
          \sigma \sqrt{\frac{1}{15} + \frac{1}{20}}}
        \sim N(0, 1)
\]</span></p>
<p>et que</p>
<p><span class="math display">\[
        \frac{14 S_1^2}{\sigma^2} + \frac{19 S_2^2}{\sigma^2}
        \sim \chi^2(33),
\]</span> on établit que</p>
<p><span class="math display">\[
        \frac{(\bar{X} - \bar{Y}) - (\mu_1 - \mu_2)}{\sqrt{\frac{14
              S_1^2 + 19 S_2^2}{33} \left( \frac{1}{15} + \frac{1}{20}
            \right)}} \sim t(33).
\]</span></p>
<p>De plus, <span class="math inline">\(t_{0,05}(33) \approx z_{0,05} = 1,645\)</span>, d’où l’intervalle de confiance à <span class="math inline">\(90~\%\)</span> pour <span class="math inline">\(\mu_1 - \mu_2\)</span> est</p>
<p><span class="math display">\[
        \mu_1 - \mu_2 \in -2 \pm 5,82.
\]</span></p>
<p>La différence de taille moyenne entre les deux groupes d’étudiantes n’est donc pas significative.</p>
<p><strong>d)</strong> Tel que mentionné précédemment, <span class="math display">\[ Y = \frac{14 S_1^2}{\sigma_1^2} \sim \chi^2(14). \]</span> Or, on trouve dans une table de la loi khi carré (ou avec la fonction <code>qchisq</code> dans R) que <span class="math display">\[ \Prob{6,57 &lt; Y &lt; 23,68} = 0,90. \]</span></p>
<p>Par conséquent,</p>
<p><span class="math display">\[
\Prob{ 6,57 &lt; \frac{14 S_1^2}{\sigma_1^2} &lt; 23,68 } = 0,90
\]</span></p>
<p>ou, de manière équivalente,</p>
<p><span class="math display">\[
\Prob{ \frac{14 S_1^2}{23,68} &lt; \sigma_1^2 &lt; \frac{14 S_1^2}{6,57} } = 0,90.
\]</span></p>
<p>Puisque <span class="math inline">\(s_1^2 = 101\)</span> dans cet exemple, un intervalle de confiance à <span class="math inline">\(90~%\)</span> pour <span class="math inline">\(\sigma_1^2\)</span> est <span class="math inline">\((59,71, \, 215,22)\)</span>.</p>
<p><strong>e)</strong> Un peu comme en c), on détermine un intervalle de confiance pour le ratio <span class="math inline">\(\sigma_2^2/\sigma_1^2\)</span> et on conclut que la différence entre la variance des étudiantes en génie civil n’est pas significativement plus grande que celle des étudiantes en actuariat si cet intervalle contient la valeur <span class="math inline">\(1\)</span>. À la suite des conclusions en c), il est raisonnable de supposer que les moyennes des deux populations sont identiques, soit <span class="math inline">\(\mu_1 = \mu_2 = \mu\)</span>. On a que <span class="math display">\[ F = \frac{S_1^2/\sigma_1^2}{S_2^2/\sigma_2^2} \sim F(14, 19). \]</span> On trouve dans une table de la loi <span class="math inline">\(F\)</span> (ou avec la fonction <code>qf</code> dans R) que <span class="math display">\[ \Prob{0,417 &lt; F &lt; 2,256} = 0,90. \]</span> Par conséquent, <span class="math display">\[ \Prob{ \frac{0,417 S_2^2}{ S_1^2} &lt; \frac{\sigma_2^2}{\sigma_1^2} &lt; \frac{2,256 S_2^2}{ S_1^2} } = 0,90 \]</span> et un intervalle de confiance à <span class="math inline">\(90~\%\)</span> pour <span class="math inline">\(\sigma_2^2/\sigma_1^2\)</span> est <span class="math inline">\((0,462, \, 2,502)\)</span>. La variance <span class="math inline">\(\sigma_2^2\)</span> n’est donc pas significativement plus grande que <span class="math inline">\(\sigma_1^2\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-intervalle_sigma" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="sec-intervalle-intervalle_sigma"><span class="header-section-number">5.6</span> Estimateur par intervalle pour <span class="math inline">\(\sigma\)</span></h2>
<p>Soit <span class="math inline">\(X_1, \dots, X_n\)</span> un échantillon aléatoire tiré d’une population normale de moyenne et variance inconnues. Développer la formule d’un estimateur par intervalle de niveau <span class="math inline">\(1 - \alpha\)</span> pour <span class="math inline">\(\sigma\)</span>, l’écart type de la distribution normale.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\((\sqrt{(n-1) S^2/b}, \sqrt{(n-1) S^2/a})\)</span>.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On sait que <span class="math display">\[
      \frac{(n-1)S^2}{\sigma^2} \sim \chi^2(n-1).
    \]</span> Ainsi, pour des constantes <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span>, <span class="math inline">\(a \leq b\)</span>, on a <span class="math display">\[
      \Prob{a \leq \frac{(n-1)S^2}{\sigma^2} \leq b} =
      \Prob{\sqrt{\frac{(n-1)S^2}{b}} \leq \sigma \leq \sqrt{\frac{(n-1)S^2}{a}}} =
      1 - \alpha.
    \]</span> Un estimateur par intervalle de <span class="math inline">\(\sigma\)</span> est donc <span class="math inline">\((\sqrt{(n-1)
      S^2/b}, \sqrt{(n-1) S^2/a})\)</span>, où <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> satisfont la relation <span class="math inline">\(\prob{a \leq Y \leq b} = 1 - \alpha\)</span>, avec <span class="math inline">\(Y \sim \chi^2(n - 1)\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-taille_longueur_intervalle" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="sec-intervalle-taille_longueur_intervalle"><span class="header-section-number">5.7</span> Taille d’échantillon pour obtenir une certaine longueur d’intervalle</h2>
<p>Soit <span class="math inline">\(X_1, X_2, \dots, X_n\)</span> un échantillon aléatoire d’une distribution normale de moyenne <span class="math inline">\(\mu\)</span> et de variance <span class="math inline">\(\sigma^2 =
  25\)</span>. Déterminer la taille de l’échantillon nécessaire pour que la longueur de l’intervalle de confiance de niveau <span class="math inline">\(0,90\)</span> pour la moyenne ne dépasse pas <span class="math inline">\(0,05\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>108241</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On sait que <span class="math display">\[
\begin{aligned}
      \mu &amp;\in \bar{X} \pm z_{0,05} \frac{\sigma}{\sqrt{n}} \\
      &amp;\in \bar{X} \pm 1,645 \frac{5}{\sqrt{n}}.
    \end{aligned}
\]</span> La longueur de l’intervalle de confiance est <span class="math inline">\(2 (1,645) (5) /
    \sqrt{n} = 16,45/\sqrt{n}\)</span>. Si l’on souhaite que <span class="math inline">\(16,45/\sqrt{n}
    \leq 0,05\)</span>, alors <span class="math inline">\(n \geq 108 241\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-taille_longueur_minimale" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="sec-intervalle-taille_longueur_minimale"><span class="header-section-number">5.8</span> Conditions pour obtenir une longueur minimale d’intervalle de confiance</h2>
<p>Soit <span class="math inline">\(S^2_n\)</span> la variance échantillonnale d’un échantillon aléatoire de taille <span class="math inline">\(n\)</span> issu d’une distribution <span class="math inline">\(\mathcal{N}(\mu, \sigma^2)\)</span> où <span class="math inline">\(\mu\)</span> et <span class="math inline">\(\sigma^2\)</span> sont des paramètres inconnus. On sait que <span class="math inline">\(Y = (n-1)S^2_n/\sigma^2 \sim
  \chi^2(n - 1)\)</span>. Soit <span class="math inline">\(g(y)\)</span> la fonction de densité de <span class="math inline">\(Y\)</span> et <span class="math inline">\(G(y)\)</span> la fonction de répartition. Soit <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> des constantes telles que <span class="math inline">\(((n-1) s^2/b, (n-1) s^2/a)\)</span> est un intervalle de confiance de niveau <span class="math inline">\(1- \alpha\)</span> pour <span class="math inline">\(\sigma^2\)</span>. La longueur de cet intervalle est donc <span class="math inline">\((n-1)  s^2 (b - a)/(ab)\)</span>. Démontrer que la longueur de l’intervalle de confiance est minimale si <span class="math inline">\(a\)</span> et <span class="math inline">\(b\)</span> satisfont la condition <span class="math inline">\(a^2  g(a) = b^2 g(b)\)</span>.</p>
<p><em>Astuce:</em> minimiser la longueur de l’intervalle sous la contrainte que <span class="math inline">\(G(b) - G(a) = 1 - \alpha\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>On cherche à minimiser la longueur de l’intervalle de confiance <span class="math inline">\(h(a, b) = (n-1) s^2 (b - a)/(ab)\)</span> sous la contrainte que la probabilité dans cet intervalle est <span class="math inline">\(1 - \alpha\)</span>, c’est-à-dire que <span class="math inline">\(G(b) - G(a) = 1 - \alpha\)</span>. En utilisant la méthode des multiplicateurs de Lagrange, on pose <span class="math display">\[
      L(a, b, \lambda) = \frac{(n-1) s^2}{a} - \frac{(n-1) s^2}{b} +
      \lambda(G(b) - G(a) - 1 + \alpha).
    \]</span> Les dérivées de cette fonction par rapport à chacune de ses variables sont: <span class="math display">\[
\begin{aligned}
      \frac{\partial}{\partial a}  L(a, b, \lambda)
      &amp;= - \frac{(n-1) s^2}{a^2} + \lambda g(a) \\
      \frac{\partial}{\partial b}  L(a, b, \lambda)
      &amp;= - \frac{-(n-1) s^2}{b^2} + \lambda g(b) \\
      \frac{\partial}{\partial \lambda}  L(a, b, \lambda)
      &amp;= G(b) - G(a) - 1 + \alpha.
    \end{aligned}
\]</span> En posant ces dérivées égales à zéro et en résolvant, on trouve que <span class="math display">\[
      \frac{g(a)}{g(b)} = \frac{b^2}{a^2}
    \]</span> ou, de manière équivalente, que <span class="math inline">\(b^2 g(b) = a^2 g(a)\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-resultats_sat" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="sec-intervalle-resultats_sat"><span class="header-section-number">5.9</span> Résultats au SAT</h2>
<p>Le <em>Scholastic Assessment Test</em> (SAT) est un test d’aptitudes standardisé largement utilisé dans les admissions aux universités américaines. Les résultats au test, qui avaient lentement diminués au fil des ans depuis son implantation, ont commencé à remonter. Initialement, un résultat de 500 était considéré dans la moyenne. En 2005, les résultats moyens étaient approximativement de 508 pour le test de langue et 520 pour le test de mathématiques. Un échantillon aléatoire de résultats de 20 étudiants d’une école secondaire a produit les moyennes et écart-types listés ci-dessous. On suppose que les résultats aux tests sont normalement distribués.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Langue</th>
<th style="text-align: center;">Mathématiques</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Moyenne échantillonnale</td>
<td style="text-align: center;">505</td>
<td style="text-align: center;">495</td>
</tr>
<tr class="even">
<td style="text-align: left;">Écart-type échantillonnal</td>
<td style="text-align: center;">55</td>
<td style="text-align: center;">70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>a)</strong> Trouver un intervalle de confiance bilatéral à <span class="math inline">\(90~\%\)</span> pour la moyenne des résultats du test de langue des étudiants de l’école secondaire.</p>
<p><strong>b)</strong> Est-ce que l’intervalle trouvé en a) inclut la valeur 508, la moyenne exacte du test de langue en 2005? Que peut-on en conclure?</p>
<p><strong>c)</strong> Trouver un intervalle de confiance bilatéral à <span class="math inline">\(90~\%\)</span> pour la moyenne des résultats du test de mathématiques des étudiants de l’école secondaire. Est-ce que l’intervalle inclut la valeur 520, la moyenne du test de mathématiques en 2005? Que peut-on en conclure?</p>
<p><strong>d)</strong> Peut-on utiliser la méthode discutée en classe pour un construire un intervalle de confiance bilatéral pour la différence entre les moyennes des deux tests (langue et mathématiques), en supposant que leur variance est égale? Expliquer.</p>
<p><strong>e)</strong> Construire un intervalle de confiance bilatéral de niveau <span class="math inline">\(90~\%\)</span> pour la variance <span class="math inline">\(\sigma^2\)</span> des résultats au test de mathématiques. Comment peut-on construire un intervalle de confiance bilatéral à <span class="math inline">\(90~\%\)</span> pour <span class="math inline">\(\sigma\)</span>? Expliquer.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <span class="math inline">\((483.734,  526.266)\)</span></p>
<p><strong>b)</strong> Oui</p>
<p><strong>c)</strong> <span class="math inline">\((467.935,   522.065)\)</span></p>
<p><strong>d)</strong> Non</p>
<p><strong>e)</strong> <span class="math inline">\((55.575,   95.929)\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> L’intervalle de confiance bilatéral pour <span class="math inline">\(\mu\)</span> a la forme <span class="math display">\[ \left[ \bar X_n - t_{n-1,\alpha/2} \frac{S_n}{\sqrt{n}}, \bar X_n + t_{n-1,\alpha/2} \frac{S_n}{\sqrt{n}} \right]. \]</span> Sachant que <span class="math inline">\(n=20\)</span> et <span class="math inline">\(\alpha =0,1\)</span>, le quantile approprié de la distribution de Student est <span class="math display">\[ t_{19,   0,05} = 1.729. \]</span> Avec <span class="math inline">\(\bar x_n = 505\)</span> et <span class="math inline">\(S_n = 55\)</span>, l’intervalle devient</p>
<p><span class="math display">\[
\begin{aligned} \left[ 505 -  1.729   \frac{55}{\sqrt{20}}   , 505 + 1.729   \frac{55}{\sqrt{20}} \right] = [ 483.734 , 526.266]. \end{aligned}
\]</span></p>
<p><strong>b)</strong> Puisque l’intervalle inclut <span class="math inline">\(508\)</span>, il n’y a pas de preuve à l’effet que la moyenne du test de langue a significativement changé depuis 2005, à un niveau de confiance <span class="math inline">\(90~\%\)</span>.</p>
<p><strong>c)</strong> L’intervalle a la même forme qu’en a) et le même quantile. Avec la moyenne échantillonnale et l’écart-type échantillonnal, l’intervalle peut être calculé comme suit <span class="math display">\[
\begin{aligned} \left[ 495 -  1.729   \frac{70}{\sqrt{20}}  ,495 + 1.729   \frac{70}{\sqrt{20}} \right] = [ 467.935,  522.065 ]. \end{aligned}
\]</span></p>
<p>L’intervalle inclut <span class="math inline">\(520\)</span>, il n’y a donc pas une différence significative dans la moyenne du test de mathématiques depuis 2005, à un niveau de confiance <span class="math inline">\(90~\%\)</span>.</p>
<p><strong>d)</strong> Non, la méthode ne peut pas être utilisée car les échantillons ne sont pas indépendants, les tests ont été effectués par les 20 mêmes étudiants dans les deux cas.</p>
<p><strong>e)</strong> L’intervalle de confiance a la forme</p>
<p><span class="math display">\[
\left[\frac{n-1}{\chi^2_{n-1,\alpha/2}}   S_n^2,\frac{n-1}{\chi^2_{n-1,1-\alpha/2}}   S_n^2\right].
\]</span></p>
<p>Les quantiles appropriés d’une distribution khi-carrée avec <span class="math inline">\(n-1=19\)</span> degrés de liberté et <span class="math inline">\(\alpha=0,1\)</span> sont <span class="math display">\[
\chi^2_{n-1,1-\alpha/2} = 10.117, \quad \chi^2_{n-1,\alpha/2} = 30.144.
\]</span> Avec la variance échantillonnale <span class="math inline">\(S_n^2 = 70^2 = 4900\)</span>, on obtient <span class="math display">\[
\begin{aligned} \left[\frac{19}{30.144}\times4900,\frac{19}{10.117}\times4900\right] = [3088.557, 9202.321]. \end{aligned}
\]</span></p>
<p>Une possibilité d’intervalle de confiance bilatéral à <span class="math inline">\(100 \times (1-\alpha)\)</span>~% pour <span class="math inline">\(\sigma\)</span> est <span class="math display">\[
\left[\sqrt{\frac{n-1}{\chi^2_{n-1,\alpha/2}}} \, S_n,\sqrt{\frac{n-1}{\chi^2_{n-1,1-\alpha/2}}} \, S_n\right],
\]</span> car</p>
<p><span class="math display">\[\begin{align*}
\Pr\left(\sqrt{\frac{n-1}{\chi^2_{n-1,\alpha/2}}} \, S_n \le \sigma \le \sqrt{\frac{n-1}{\chi^2_{n-1,1-\alpha/2}}} \, S_n \right)\\ &amp;= \Pr\left(\frac{n-1}{\chi^2_{n-1,\alpha/2}} \, S_n^2 \le \sigma^2 \le \frac{n-1}{\chi^2_{n-1,1-\alpha/2}} \, S_n^2 \right) = 1-\alpha.
\end{align*}\]</span></p>
<p>L’intervalle devient <span class="math display">\[\begin{align*}
[\sqrt{3088.557} ,\sqrt{9202.321}] = [55.575, 95.929].
\end{align*}\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-laboratoires_cuivre" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="sec-intervalle-laboratoires_cuivre"><span class="header-section-number">5.10</span> Laboratoires de production de cuivre</h2>
<p>Le cuivre solide produit par frittage (chauffage sans fusion) d’une poudre dans des conditions environnementales spécifiques est ensuite mesuré pour la porosité (la fraction volumique due aux vides) en laboratoire. Un échantillon de <span class="math inline">\(n=4\)</span> mesures de porosité indépendantes a une moyenne <span class="math inline">\(\bar x_n = 0,22\)</span> et une variance <span class="math inline">\(s_n^2 = 0,001\)</span>. Un second laboratoire répète le même processus et obtient <span class="math inline">\(m=5\)</span> mesures de porosité indépendantes avec <span class="math inline">\(\bar y_m = 0,17\)</span> and <span class="math inline">\(s_m^2 = 0,002\)</span>.</p>
<p><strong>a)</strong> Énumérer les hypothèses nécessaires pour construire un intervalle de confiance bilatéral <em>exact</em> pour la différence de moyennes entre les populations des deux laboratoires.</p>
<p><strong>b)</strong> Construire un intervalle de confiance bilatéral <em>exact</em> à <span class="math inline">\(95~\%\)</span> pour la différence des moyennes des populations des deux laboratoires.</p>
<p><strong>c)</strong> Est-ce que la différence entre les moyennes des deux laboratoires est significative?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="2" type="a">
<li><span class="math inline">\((-0.01288,  0.11288)\)</span></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Les échantillons doivent être indépendants, normalement distribués et avoir la même variance <span class="math inline">\(\sigma^2\)</span>.</p>
<p><strong>b)</strong> L’estimation combinée de la variance est donnée par <span class="math display">\[
s^2 = \frac{(n-1) s_n^2 + (m-1)s_m^2}{n+m-2} = \frac{3\times 0,001 + 4 \times 0,002}{4+5-2} = 0.00157.
\]</span> Le quantile <span class="math inline">\(97,5~\%\)</span> de la loi de Student avec <span class="math inline">\(n+m-2=7\)</span> degrés de liberté est <span class="math display">\[
t_{0,025, \, 7} = 2.365.
\]</span></p>
<p>L’intervalle de confiance à <span class="math inline">\(95~\%\)</span> est donc donné par</p>
<p><span class="math display">\[
\begin{aligned}
&amp;\left[\bar x_n - \bar y_m - t_{0,025, \, 7} s \sqrt{\frac{1}{n} + \frac{1}{m}} \, , \bar x_n - \bar y_m + t_{0,025, \, 7} s \sqrt{\frac{1}{n} + \frac{1}{m}}\right] \\
&amp;= \left[0,22 - 0,17 - t_{0,025, \, 7} s \sqrt{\frac{1}{4} + \frac{1}{5}}, 0,22 - 0,17 + t_{0,025, \, 7} s \sqrt{\frac{1}{4} + \frac{1}{5}}\right] \\
&amp;= [-0.01288 \, ,0.11288].
\end{aligned}
\]</span></p>
<p><strong>c)</strong> Puisque <span class="math inline">\(0\)</span> est inclus dans l’intervalle de confiance bilatéral calculé en b), les moyennes ne semblent pas différer à un seuil de <span class="math inline">\(5~\%\)</span>.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-aines_cycles_superieurs" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="sec-intervalle-aines_cycles_superieurs"><span class="header-section-number">5.11</span> Enfants aînés aux cycles supérieurs</h2>
<p>Dans une étude sur la relation entre l’ordre de naissance et la réussite scolaire, un chercheur a trouvé que <span class="math inline">\(126\)</span> étudiants aux cycles supérieurs sur un échantillon de <span class="math inline">\(180\)</span> étaient enfants ainés. Dans un échantillon de <span class="math inline">\(100\)</span> personnes n’étudiant pas aux cycles supérieurs d’âge et de situation socio-économique comparable, le nombre d’ainés étaient de <span class="math inline">\(54\)</span>.</p>
<p><strong>a)</strong> Construire un intervalle de confiance bilatéral approximatif à <span class="math inline">\(90~\%\)</span> pour la différence entre les proportions d’ainés pour les deux populations desquelles proviennent les échantillons.</p>
<p><strong>b)</strong> Basé sur l’intervalle en a), est-ce que la différence entre les proportions d’ainés des deux populations semble significative?</p>
<p><strong>c)</strong> Si les chercheurs souhaitent questionner un nombre égal <span class="math inline">\(n\)</span> d’étudiants aux cycles supérieurs et de personnes qui ne le sont pas, quelle est la valeur minimale de <span class="math inline">\(n\)</span> requise pour estimer la différence entre les proportions avec une erreur inférieure ou égale à <span class="math inline">\(\pm 0.05\)</span> avec un niveau de confiance de <span class="math inline">\(90~\%\)</span>?</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> <span class="math inline">\((0.06062,  0.25938)\)</span></p>
<p><strong>b)</strong> Non</p>
<p><strong>c)</strong> <span class="math inline">\(n \geq 542\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> Les proportions échantillonnales sont <span class="math display">\[ p_n = \frac{126}{180}=0,7, \quad q_m = \frac{54}{100}=0,54. \]</span> Les tailles d’échantillons sont respectivement de <span class="math inline">\(n=180\)</span> et <span class="math inline">\(m=100\)</span>. Puisque les deux sont assez grandes, une approximation d’un intervalle de confiance à <span class="math inline">\(90~\%\)</span> peut être utilisée pour <span class="math inline">\(p-q\)</span>.</p>
<p>D’abord, comme <span class="math display">\[\var{p - q} = \var{p} + \var{q},\]</span> on estime que <span class="math display">\[ \widehat{\var{p - q}} = \var{\bar{X}_n} + \var{\bar{Y}_m} = \frac{p_n(1 - p_n)}{n} + \frac{q_m(1-q_m)}{m}.\]</span></p>
<p>Ainsi, par la méthode de l’intervalle de confiance approximatif pour grands échantillons, on a que <span class="math inline">\(\hat{\theta} \pm z_{0.05} \sqrt{\widehat{\var{\theta}}}\)</span> et on trouve <span class="math display">\[
\left[ p_n - q_m - z_{0,05} \sqrt{\frac{p_n(1-p_n)}{n} + \frac{q_m(1-q_m)}{m}},  p_n - q_m + z_{0,05} \sqrt{\frac{p_n(1-p_n)}{n} + \frac{q_m(1-q_m)}{m}}\right].
\]</span> Le quantile <span class="math inline">\(95~\%\)</span> d’une loi <span class="math inline">\(\mathcal{N}(0,1)\)</span> est <span class="math display">\[
z_{0,05} = 1.645.
\]</span> L’intervalle de confiance devient <span class="math display">\[
\begin{aligned}
\left [0.16 - 1.645 \sqrt{\frac{0.7 \times 0.3}{180} + \frac{0.54\times 0.46}{100}} \, , 0.16 + 1.645 \sqrt{\frac{0.7 \times 0.3}{180} + \frac{0.54\times 0.46}{100}}\right] \\ = [0.06062, 0.25938].
\end{aligned}
\]</span></p>
<p><strong>b)</strong> Puisque l’intervalle de confiance calculé en a) ne contient pas <span class="math inline">\(0\)</span>, la proportion d’enfants ainés semble être significativement plus grande dans la population d’étudiants aux cycles supérieurs au niveau de confiance <span class="math inline">\(90~\%\)</span>.</p>
<p><strong>c)</strong> En supposant <span class="math inline">\(n=m\)</span>, la taille d’échantillon de chaque groupe peut être calculée en résolvant l’équation <span class="math display">\[
1.645\sqrt{\frac{p(1-p)}{n} + \frac{q(1-q)}{n}} = 0,05.
\]</span> On trouve <span class="math display">\[
n = \left(\frac{1.645}{0.05}\right)^2 \{ p(1-p)+ q(1-q)\}.
\]</span> Sachant que pour tout <span class="math inline">\(p\in(0,1)\)</span>, <span class="math inline">\(p(1-p) \le 1/4\)</span>, une estimation conservatrice des tailles d’échantillon requises est</p>
<p><span class="math display">\[
n = m=  \left(\frac{1.645}{0.05}\right)^2 \times \left(\frac{1}{4} + \frac{1}{4} \right) \approx 541.205.
\]</span></p>
<p>Ainsi, pour atteindre la précision requise, chaque groupe doit comprendre au moins <span class="math inline">\(542\)</span> personnes.</p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-intervalle_mle_exponentielle" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="sec-intervalle-intervalle_mle_exponentielle"><span class="header-section-number">5.12</span> Intervalle de confiance avec l’estimateur du maximum de vraisemblance d’une distribution exponentielle</h2>
<p>Soit <span class="math inline">\(X_1,\ldots,X_n\)</span> un échantillon aléatoire d’une distribution exponentielle avec densité <span class="math display">\[
f(x)=\lambda e^{-\lambda x}, \quad x&gt;0.
\]</span> <strong>a)</strong> Écrire la vraisemblance, la log-vraisemblance et l’EMV de <span class="math inline">\(\lambda\)</span>.</p>
<p><strong>b)</strong> Calculer l’information de Fisher <span class="math inline">\(I(\lambda)\)</span>.</p>
<p><strong>c)</strong> Si <span class="math inline">\(m=100\)</span> et <span class="math inline">\(\bar x=105,2\)</span>, utiliser la distribution limite de l’EMV pour obtenir un intervalle de confiance approximatif <span class="math inline">\(95~\%\)</span> pour <span class="math inline">\(\lambda\)</span>.</p>
<p><strong>d)</strong> Basé sur l’intervalle trouvé en c), obtenir un intervalle de confiance approximatif de niveau <span class="math inline">\(95~\%\)</span> pour la probabilité <span class="math inline">\(\Pr[X&gt;300]\)</span>, où <span class="math inline">\(X\)</span> est indépendant de <span class="math inline">\(X_1,\ldots,X_n\)</span> et a la même distribution.</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol start="3" type="a">
<li><span class="math inline">\([0.00764, 0.01137]\quad\)</span></li>
<li><span class="math inline">\([0.03302, 0.10099]\)</span></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> La vraisemblance est <span class="math display">\[
L(\lambda)=\prod_{i=1}^n \lambda e^{-\lambda x_i} = \lambda^n e^{-\lambda\sum_{i=1}^n x_i}
\]</span> et la log-vraisemblance est</p>
<p><span class="math display">\[
\ell(\lambda)=n\ln\lambda-\lambda\sum_{i=1}^n x_i.
\]</span></p>
<p>Si on dérive par rapport à <span class="math inline">\(\lambda\)</span>, on trouve <span class="math display">\[ \ell'(\lambda)=\frac{n}{\lambda}-\sum_{i=1}^n x_i \]</span> et <span class="math inline">\(\ell''(\lambda)=-n/\lambda^2&lt;0\)</span>, donc l’estimateur du maximum de vraisemblance est</p>
<p><span class="math display">\[
\frac{n}{\hat\lambda}-\sum_{i=1}^n x_i=0 \quad \Rightarrow \hat\lambda=\frac{1}{\bar x_n}.
\]</span></p>
<p><strong>b)</strong> On a <span class="math inline">\(\ln f(X;\lambda) = \ln\lambda-\lambda X\)</span> donc l’information de Fisher est <span class="math display">\[
\begin{aligned} I(\lambda)&amp;=\ex\left[-\frac{\partial^2}{\partial\lambda^2} \ln f(X;\lambda) \right]=\ex\left[-\frac{\partial^2}{\partial\lambda^2} \left(\ln\lambda-\lambda X \right)\right]=\ex\left[\frac{1}{\lambda^2} \right] =\frac{1}{\lambda^2}. \end{aligned}
\]</span></p>
<p><strong>c)</strong> La distribution limite de l’EMV est</p>
<p><span class="math display">\[
\frac{\hat\lambda_n-\lambda}{\sqrt{1/\{nI(\lambda)\}}}
\]</span> est asymptotiquement <span class="math inline">\(\mathcal{N}(0,1)\)</span>. On peut estimer <span class="math inline">\(nI(\lambda)\)</span> au dénominateur par <span class="math inline">\(nI(\hat\lambda)=\frac{n}{\hat\lambda^2}\)</span>, pour obtenir, quand <span class="math inline">\(n\to\infty\)</span>,</p>
<p><span class="math display">\[
\frac{\hat\lambda-\lambda}{\hat\lambda/\sqrt{n}}
\]</span> est asymptotiquement <span class="math inline">\(\mathcal{N}(0,1)\)</span>. D’une autre façon, on peut estimer <span class="math inline">\(nI(\lambda)\)</span> par</p>
<p><span class="math display">\[
-\left.\frac{\partial^2}{\partial\lambda^2} \ell(\lambda)\right|_{\lambda=\hat\lambda}=\frac{n}{\hat\lambda^2},
\]</span> ce qui revient à la même réponse.</p>
<p>Sachant que <span class="math inline">\(z_{2,5\%}=1.96\)</span> et <span class="math inline">\(\hat\lambda=1/\bar x=1/105,2\)</span>, un intervalle de confiance approximatif de niveau <span class="math inline">\(95~\%\)</span> pour <span class="math inline">\(\lambda\)</span> est</p>
<p><span class="math display">\[
\begin{align*}
\left[\hat\lambda-z_{\alpha/2}\sqrt{\frac{\hat\lambda^2}{n}},\hat\lambda+z_{\alpha/2}\sqrt{\frac{\hat\lambda^2}{n}}\right]&amp;=\left[\frac{1}{\bar x_n}-z_{\alpha/2}\frac{1}{\sqrt{n}\bar x_n}, \frac{1}{\bar x_n}+z_{\alpha/2}\frac{1}{\sqrt{n}\bar x_n}\right]\\
&amp;=\left[\frac{1}{105.2}-\frac{1.96}{10\times105.2},\frac{1}{105.2}+\frac{1.96}{10\times105.2}\right]\\
&amp;=\left[0.00764,0.01137\right].
\end{align*}
\]</span></p>
<p><strong>d)</strong> Le paramètre d’intérêt est <span class="math inline">\(\theta=\Pr[X&gt;300]=e^{-300\lambda}\)</span>. On a</p>
<p><span class="math display">\[
\begin{aligned} \Pr\left[\frac{1}{\bar X_n}-z_{\alpha/2}\frac{1}{\sqrt{n}\bar X_n}\leq \lambda \leq \frac{1}{\bar X_n}+z_{\alpha/2}\frac{1}{\sqrt{n}\bar X_n}\right]\approx 0,95. \end{aligned}
\]</span></p>
<p>Multiplier l’inégalité par <span class="math inline">\(-300\)</span> change le signe d’inégalité, alors que l’exponentielle est une fonction croissante, donc</p>
<p><span class="math display">\[
\begin{aligned} \Pr\left[\exp\left\{-300\left(\frac{1}{\bar X_n}-z_{\alpha/2}\frac{1}{\sqrt{n}\bar X_n}\right)\right\}\geq e^{-300\lambda} \geq \exp\left\{-300\left(\frac{1}{\bar X_n}+z_{\alpha/2}\frac{1}{\sqrt{n}\bar X_n}\right)\right\}\right]\approx 0,95. \end{aligned}
\]</span></p>
<p>Donc, un intervalle de confiance de niveau approximatif <span class="math inline">\(95~\%\)</span> pour <span class="math inline">\(\Pr[X&gt;300]\)</span> est</p>
<p><span class="math display">\[
\left[0.03302, 0.10099\right].
\]</span></p>
</div>
</div>
</div>
</section>
<section id="sec-intervalle-intervalle_mle_bernoulli" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="sec-intervalle-intervalle_mle_bernoulli"><span class="header-section-number">5.13</span> Intervalle de confiance avec l’estimateur du maximum de vraisemblance d’une distribution Bernoulli</h2>
<p>Soit <span class="math inline">\(X_1,\ldots,X_n\)</span> un échantillon aléatoire d’une distribution Bernoulli avec paramètre inconnu <span class="math inline">\(\theta\)</span>.</p>
<p><strong>a)</strong> Écrire la vraisemblance, la log-vraisemblance et l’EMV de <span class="math inline">\(\theta\)</span>.</p>
<p><strong>b)</strong> Calculer l’information de Fisher <span class="math inline">\(I(\theta)\)</span>.</p>
<p><strong>c)</strong> Si <span class="math inline">\(m=144\)</span> et <span class="math inline">\(\bar x=0,126\)</span>, utiliser la distribution limite de l’EMV pour obtenir un intervalle de confiance approximatif à <span class="math inline">\(96\)</span><br>
</p>
<div class="callout callout-style-default callout-note callout-titled" title="Éléments de réponse">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Éléments de réponse
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>a)EMV: <span class="math inline">\(\bar{x}_n \quad\)</span> b) <span class="math inline">\(I(\theta) = \frac{1}{\theta(1 - \theta)}\)</span> c) <span class="math inline">\([0,0692;0,01828]\quad\)</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled" title="Solution complète">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Astuce</span>Solution complète
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a)</strong> La vraisemblance est <span class="math display">\[ L(\theta)=\prod_{i=1}^n \theta^{x_i}(1-\theta)^{1 - x_i} = \theta^{\sum_{i=1}^n x_i} (1 - \theta)^{n - \sum_{i = 1}^n x_i} \]</span> et la log-vraisemblance est <span class="math display">\[ \ell(\theta)= \sum_{i=1}^n x_i \ln\theta + (n - \sum_{i = 1}^n x_i) \ln(1-\theta). \]</span> Si on dérive par rapport à <span class="math inline">\(\lambda\)</span>, on trouve <span class="math display">\[ \ell'(\theta)=\frac{\sum_{i=1}^n x_i}{\theta}- \frac{(n - \sum_{i=1}^n x_i)}{1 - \theta}, \]</span> donc l’estimateur du maximum de vraisemblance est <span class="math display">\[ \frac{\sum_{i=1}^n x_i}{\theta}- \frac{(n - \sum_{i=1}^n x_i)}{1 - \theta}=0 \quad \Rightarrow \hat\theta=\bar x_n. \]</span></p>
<p><strong>b)</strong> On a <span class="math inline">\(\ln f(x;\theta) = x\ln\theta-\ln(1 - \theta) (1 - x)\)</span> donc l’information de Fisher est <span class="math display">\[
\begin{aligned} I(\theta)&amp;=\ex\left[-\frac{\partial^2}{\partial\theta^2} \ln f(X;\theta) \right]=\ex\left[-\frac{\partial^2}{\partial\theta^2} \left(X\ln\theta-\ln(1 - \theta) (1 - X) \right)\right]=\ex\left[\frac{X}{\theta^2} + \frac{1 - X}{(1 - \theta)^2} \right] =\frac{1}{\theta (1 - \theta)}. \end{aligned}
\]</span></p>
<p><strong>c)</strong> La distribution limite de l’EMV est <span class="math display">\[ \frac{\hat\theta_n-\theta}{\sqrt{1/\{nI(\theta)\}}} \]</span> est asymptotiquement <span class="math inline">\(\mathcal{N}(0,1)\)</span>. On peut estimer <span class="math inline">\(nI(\lambda)\)</span> au dénominateur par <span class="math inline">\(nI(\hat\theta)=\frac{n}{\hat\theta(1 - \theta)}\)</span>, pour obtenir, quand <span class="math inline">\(n\to\infty\)</span>, <span class="math display">\[ \frac{\hat\theta-\theta}{\hat\theta/\sqrt{n}} \]</span> est asymptotiquement <span class="math inline">\(\mathcal{N}(0,1)\)</span>. D’une autre façon, on peut estimer <span class="math inline">\(nI(\theta)\)</span> par <span class="math display">\[ -\left.\frac{\partial^2}{\partial\lambda^2} \ell(\theta)\right|_{\theta=\hat\theta}=\frac{n}{\hat\theta (1 - \hat\theta)}, \]</span> ce qui revient à la même réponse. Sachant que <span class="math inline">\(z_{2\%}=2.054\)</span> et <span class="math inline">\(\hat\theta=\bar x=0,126\)</span>, un intervalle de confiance approximatif de niveau <span class="math inline">\(96~\%\)</span> pour <span class="math inline">\(\theta\)</span> est</p>
<p><span class="math display">\[
\begin{align*}
\left[\hat\theta-z_{\alpha/2}\sqrt{\frac{\hat\theta(1 - \hat\theta)}{n}},\hat\theta+z_{\alpha/2}\sqrt{\frac{\hat\theta(1 - \hat\theta)}{n}}\right]&amp;=\left[\bar x_n-z_{\alpha/2}\sqrt{\frac{\bar{x}_n(1 - \bar{x}_n)}{n}}, \bar x_n+z_{\alpha/2}\sqrt{\frac{\bar{x}_n(1 - \bar{x}_n)}{n}}\right]\\
&amp;=0,126\pm\frac{2,054 \times \sqrt{0,126 \times 0,874}}{12} \\
&amp;=\left[0.0692, 0.1828\right].
\end{align*}
\]</span></p>
</div>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-Freund:mathstat:1992" class="csl-entry" role="listitem">
Freund, J. E. 1992. <em>Mathematical Statistics</em>. 5ᵉ éd. Prentice Hall.
</div>
<div id="ref-Hogg:mathstat:6e:2005" class="csl-entry" role="listitem">
Hogg, R. V., A. T. Craig, et J. W. McKean. 2005. <em>Introduction to Mathematical Statistics</em>. 6ᵉ éd. Prentice Hall.
</div>
<div id="ref-Hogg:probstat:2001" class="csl-entry" role="listitem">
Hogg, R. V., et E. A. Tanis. 2001. <em>Probability and Statistical Inference</em>. 6ᵉ éd. Prentice Hall.
</div>
<div id="ref-Mood:mathstat:1974" class="csl-entry" role="listitem">
Mood, A. M., F. A. Graybill, et D. C. Boes. 1974. <em>Introduction to the Theory of Statistics</em>. 3ᵉ éd. McGraw-Hill.
</div>
<div id="ref-R" class="csl-entry" role="listitem">
R Core Team. 2018. <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-Wackerly:mathstat:7e:2008" class="csl-entry" role="listitem">
Wackerly, D., W. Mendenhall, et R. L. Scheaffer. 2007a. <em>Mathematical Statistics with Applications</em>. 7ᵉ éd. Thomson Brooks/Cole. <a href="https://books.google.ca/books?id=lTgGAAAAQBAJ">https://books.google.ca/books?id=lTgGAAAAQBAJ</a>.
</div>
<div id="ref-Wackerly:solutions:7e:2008" class="csl-entry" role="listitem">
Wackerly, D., W. Mendenhall, et R. L. Scheaffer. 2007b. <em>Student’s solution manual to Mathematical Statistics with Applications</em>. 7ᵉ éd. Thomson Brooks/Cole. <a href="https://books.google.ca/books?id=lTgGAAAAQBAJ">https://books.google.ca/books?id=lTgGAAAAQBAJ</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copié");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copié");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapitres/ajustement.html" class="pagination-link" aria-label="Ajustement de modèles">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Ajustement de modèles</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapitres/tests.html" class="pagination-link" aria-label="Tests">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tests</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>