## Distribution de statistiques fondées sur un échantillon issu d'une loi normale {#sec-echantillonnage-norm_distr_statistique}

Soit $Y_1,\ldots,Y_8$ un échantillon aléatoire issu d'une distribution $\mathcal{N}(0,1)$ et
$$
\bar Y= (Y_1+\cdots+Y_7)/7.
$$
Quelle est la distribution des statistiques suivantes? Justifiez vos réponses.

**a)** $W = \sum_{i=1}^7 Y_i^2$

**b)** $U = \sum_{i=1}^7 (Y_i-\bar Y)^2$

**c)** $Y_8^2+U$

**d)** $\sqrt{7} Y_8/\sqrt{W}$

**e)** $\sqrt{6}Y_8/\sqrt{U}$

**f)** $3(7\bar Y^2+Y_8^2)/U$

::: {.callout-note collapse="true" title="Éléments de réponse"}
**a)** $\chi^2(7)$

**b)** $\chi^2(6)$

**c)** $\chi^2(7)$

**d)** $t(7)$

**e)** $t(6)$

**f)** $F(2, 6)$
:::

::: {.callout-tip collapse="true" title="Solution complète"}
**a)** La statistique $W = Y_1^2 + \cdots + Y^2_7$ suit une loi khi carré avec $7$ degrés de liberté, $\chi^2_{(7)}$, puisque $W$ est une somme de sept variables **indépendantes**, chacune d'entre elle étant le carré d'une variable aléatoire normale centrée réduite.

**b)** Si $Y_1, \ldots , Y_n$ forme un échantillon aléatoire tiré d'une $\mathcal{N}(\mu, \sigma^2)$, alors $$ \frac{(n-1)S^2_n}{\sigma^2} = \frac{1}{\sigma^2} \sum_{i=1}^n (Y_i - {\bar Y}_n)^2 $$ a une distribution khi carré avec $n-1$ degrés de liberté, $\chi^2_{(n-1)}$. Si on pose $n=7$ et $\sigma^2 =1$, on trouve que $$ U = \sum_{i=1}^7 (Y_i - {\bar Y})^2 \sim \chi^2_{(6)}. $$

**c)** Selon (b), $U$ a une distribution $\chi^2_{(6)}$. Cela signifie que la somme a la même distribution que $Z_1^2 + \cdots + Z_6^2$, où $Z_1, \ldots , Z_6$ sont iid $\mathcal{N}(0,1)$ et indépendantes de $Y_8$, qui suit aussi une $\mathcal{N}(0,1)$. Ainsi, $$ Y_8^2 +U \sim \chi^2_{(7)}. $$

**d)**  D'abord, on observe que $\sqrt{7}   Y_8 /\sqrt{W} = Y_8/\sqrt{W/7}$, où $Y_8 \sim \mathcal{N}(0,1)$ et $W \sim \chi^2_{(7)}$ selon a). De plus, $W$ et $Y_8$ sont des variables aléatoires indépendantes. Ainsi, $Y_8/\sqrt{W/7}$ suit une loi Student $t_{(7)}$.

**e)** On note que $U \sim \chi^2_{(6)}$ selon b). Ensuite, $U$ est indépendant de $Y_8 \sim \mathcal{N}(0,1)$. Ainsi, $$ \frac{\sqrt{6}Y_8}{\sqrt{U}} = \frac{Y_8}{\sqrt{U/6}} \sim t_{(6)}. $$

**f)** On sait que la moyenne échantillonnale ${\bar Y}$ est indépendante de la variance échantillonnale $U/6$. Donc, ${\bar Y}$ et $Y_8$ sont toutes deux indépendantes de $U$. Puisque ${\bar Y} \sim \mathcal{N}(0,1/7)$, on a $\sqrt{7}   {\bar Y} \sim \mathcal{N}(0,1)$ et ainsi $$ 7{\bar Y}^2 + Y^2_8 = (\sqrt{7}   {\bar Y})^2 + Y^2_8 \sim \chi^2_{(2)}. $$ De plus, $U \sim \chi^2_{(6)}$ avec (b). Il en découle que $$ \frac{3(7{\bar Y}^2 + Y^2_8)}{U} = \frac{\displaystyle \frac{(\sqrt{7}   {\bar Y})^2+Y^2_8}{2}}{U/6} \sim \mathcal{F}_{(2,6)}. $$
:::

