## Deux estimateurs sans biais de $\theta$ {#sec-estimation-biais_ech_taille3_uniforme}

Soient $X_{(1)} < X_{(2)} < X_{(3)}$ les statistiques d'ordre d'un
  échantillon aléatoire de taille $3$ tiré d'une distribution uniforme
  avec fonction de densité
  $$
    f(x) = \theta^{-1}, \quad 0 < x < \theta, \quad \theta > 0.
  $$
  Démontrer que $4 X_{(1)}$ et $2 X_{(2)}$ sont tous deux des
  estimateurs sans biais de $\theta$. Trouver la variance de chacun de
  ces estimateurs.

::: {.callout-note collapse="true" title="Éléments de réponse"}
$\var{4X_{(1)}} = 3 \theta^2/5$, $\var{2X_{(2)}} = \theta^2/5$.
:::

::: {.callout-tip collapse="true" title="Solution complète"}
La fonction de densité de probabilité de la $k$ième statistique
    d'ordre est donnée par le Théorème 6.5 des notes de cours.
    $$
    f_{X_{(k)}}(x)=\frac{n!}{(k-1)!(n-k)!}F(x)^{k-1}\{1-F(x)\}^{n-k}f(x)
    $$
    Pour $n = 3$ et $X_i \sim U(0, \theta)$, $i = 1, 2, 3$, on a
    $$
\begin{aligned}
      f_{X_{(1)}}(x)
      &= 3 \left(1 - \frac{x}{\theta} \right)^2
      \left( \frac{1}{\theta} \right) \\
      &= 3 \left(
        \frac{1}{\theta} - \frac{2x}{\theta^2} + \frac{x^2}{\theta^3}
      \right), \quad 0 < x < \theta \\
      \end{aligned}
$$

et

$$
\begin{aligned}
      f_{X_{(2)}}(x)
      &= 6 \left( \frac{x}{\theta} \right)
      \left( 1 - \frac{x}{\theta} \right)
      \left( \frac{1}{\theta} \right) \\
      &= 6 \left(
        \frac{x}{\theta^2} - \frac{x^2}{\theta^3}
      \right), \quad 0 < x < \theta.
    \end{aligned}
$$
    Ainsi, d'une part,
    $$
\begin{aligned}
      \esp{4X_{(1)}} &= 4 \int_0^{\theta} x f_{X_{(1)}}(x)  dx \\
      &= 12 \int_0^{\theta}
      \left(
        \frac{x}{\theta} - \frac{2x^2}{\theta^2} + \frac{x^3}{\theta^3}
      \right)  dx \\
      &= 12 \left(
        \frac{\theta}{2} - \frac{2 \theta}{3} + \frac{\theta}{4}
      \right) \\
      &= \theta \\
      \end{aligned}
$$

et

$$
\begin{aligned} 
      \esp{2X_{(2)}} &= 2 \int_0^{\theta} x f_{X_{(2)}}(x)  dx \\
      &= 12 \int_0^\theta
      \left(
        \frac{x^2}{\theta^2} - \frac{x^3}{\theta^3}
      \right)  dx \\
      &= 12 \left( \frac{\theta}{3} - \frac{\theta}{4} \right) \\
      &= \theta,
    \end{aligned}
$$
    d'où $4 X_{(1)}$ et $2 X_{(2)}$ sont des estimateurs sans biais de
    $\theta$. D'autre part,
    $$
\begin{aligned}
      \esp{(4X_{(1)})^2} &= 16 \int_0^{\theta} x^2 f_{X_{(1)}}(x)  dx \\
      &= 48 \int_0^{\theta}
      \left(
        \frac{x^2}{\theta} - \frac{2x^3}{\theta^2} + \frac{x^4}{\theta^3}
      \right)  dx \\
      &= 48 \left(
        \frac{\theta^2}{3} - \frac{2 \theta^2}{4} + \frac{\theta^2}{5}
      \right) \\
      &= \frac{8 \theta^2}{5} \\
      \end{aligned}
$$

et

$$
\begin{aligned}
      \esp{(2X_{(2)})^2} &= 4 \int_0^{\theta} x^2 f_{X_{(2)}}(x)  dx \\
      &= 24 \int_0^\theta
      \left(
        \frac{x^3}{\theta^3} - \frac{x^4}{\theta^3}
      \right)  dx \\
      &= 24 \left( \frac{\theta^2}{4} - \frac{\theta^2}{5} \right) \\
      &= \frac{6 \theta^2}{5}.
    \end{aligned}
$$
    Par conséquent,
    $$
\begin{aligned}
      \var{4 X_{(1)}}
      &= \frac{8 \theta^2}{5} - \theta^2 = \frac{3 \theta^2}{5} \\
      \end{aligned}
$$

et

$$
\begin{aligned}
      \var{2 X_{(2)}}
      &= \frac{6 \theta^2}{5} - \theta^2 = \frac{\theta^2}{5}.
    \end{aligned}
$$
:::

