## Efficacité relative de deux estimateurs pour une loi normale {#sec-estimation-mvue_2loisnormales}

Supposons que $\bar{X}_1$ est la moyenne d'un échantillon aléatoire
  de taille $n$ d'une population normale avec moyenne $\mu$ et
  variance $\sigma_1^2$, que $\bar{X}_2$ est la moyenne d'un
  échantillon aléatoire de taille $n$ d'une population normale avec
  moyenne $\mu$ et variance $\sigma_2^2$ et que les deux échantillons
  aléatoires sont indépendants.
**a)** Démontrer que $\omega \bar{X}_1 + (1 - \omega) \bar{X}_2$, $0 \leq \omega \leq 1$, est un estimateur sans biais de $\mu$.

**b)** Démontrer que la variance de $\omega \bar{X}_1 + (1 - \omega) \bar{X}_2$ est minimale lorsque $$ \omega = \frac{\sigma_2^2}{\sigma_1^2 + \sigma_2^2}. $$

**c)** Calculer l'efficacité relative de l'estimateur en a) avec $\omega = \frac{1}{2}$ à celle de l'estimateur à variance minimale trouvé en b).

::: {.callout-note collapse="true" title="Éléments de réponse"}
\addtocounter{enumi}{2}

**a)** $(\sigma_1^2 + \sigma_2^2)^2/(4 \sigma_1^2 \sigma_2^2)$
:::

::: {.callout-tip collapse="true" title="Solution complète"}
**a)** On a $$
\begin{aligned} \esp{\omega \bar{X}_1 + (1 - \omega)\bar{X}_2} &= \omega\Esp{\bar{X}_1} + (1 - \omega)\Esp{\bar{X}_2}\\ &= \omega\mu +(1 - \omega)\mu\\ &= \mu. \end{aligned}
$$

**b)** En premier lieu, $$
\begin{aligned} \var{\omega\bar{X}_1 - (1 - \omega)\bar{X}_2} &= \omega^2 \var{\bar{X}_1} + (1 - \omega)^2 \var{\bar{X}_2}\\ &= \frac{\omega^2 \sigma_1^2}{n} + \frac{(1 - \omega)^2 \sigma_2^2}{n} \end{aligned}
$$ Or, en résolvant l'équation $$ \frac{d}{d\omega}  \var{\omega \bar{X}_1 - (1 - \omega)\bar{X}_2} = \frac{2 \omega \sigma_1^2}{n} - \frac{2 (1 - \omega) \sigma_2^2}{n} = 0, $$ on trouve que $\omega = \sigma_2^2/(\sigma_1^2 + \sigma_2^2)$. La vérification des conditions de deuxième ordre (laissée en exercice) démontre qu'il s'agit bien d'un minimum.

**c)** Après quelques transformations algébriques, la variance de l'estimateur à son point minimum est $$ \frac{\sigma_1^2 \sigma_2^2}{n(\sigma_1^2 + \sigma_2^2)}. $$ Lorsque $\omega = 1/2$, la variance de l'estimateur est $$ \Var{\frac{\bar{X}_1 - \bar{X}_2}{2}} = \frac{\sigma_1^2 + \sigma_2^2}{4n}. $$ L'efficacité relative est donc $$
\begin{aligned} \frac{(\sigma_1^2 + \sigma_2^2)^2}{4 \sigma_1^2 \sigma_2^2} \end{aligned}
$$ (ou l'inverse).
:::

